export const TOGGLE_DATA_MENU = "TOGGLE_DATA_MENU";
export const CLOSE_DATA_MENU = "CLOSE_DATA_MENU";

export const LOAD_INITIAL_COLUMN_DATA = "LOAD_INITIAL_COLUMN_DATA";
export const CHANGE_COLUMN_DATA = "CHANGE_COLUMN_DATA";

export const FETCH_CRYPTOS_BEGIN = "FETCH_CRYPTOS_BEGIN";
export const FETCH_CRYPTOS_SUCCESS = "FETCH_CRYPTOS_SUCCESS";
export const FETCH_CRYPTOS_FAILURE = "FETCH_PRODUCTS_FAILURE";
