export const TOGGLE_DATA_MENU = "TOGGLE_DATA_MENU";
export const CLOSE_DATA_MENU = "CLOSE_DATA_MENU";

export const SET_SELECTED_DATA_TYPE = "SET_SELECTED_DATA_TYPE";
export const SET_SELECTED_DATA_GROUP = "SET_SELECTED_DATA_GROUP";
export const SET_SELECTED_DATA_PERIOD = "SET_SELECTED_DATA_PERIOD";

export const UPDATE_CURRENT_DATA = "UPDATE_CURRENT_DATA";

export const LOAD_INITIAL_COLUMN_DATA = "LOAD_INITIAL_COLUMN_DATA";
export const EMPTY_HISTOGRAM_DATA = "EMPTY_HISTOGRAM_DATA";
export const PROCESS_NEW_COLUMN_DATA = "PROCESS_NEW_COLUMN_DATA";
export const UPDATE_LIVE_COLUMN_VIEW = "UPDATE_LIVE_COLUMN_VIEW";
export const PROCESS_DATA_FROM_STORE_FOR_HISTOGRAM = "PROCESS_DATA_FROM_STORE_FOR_HISTOGRAM";

export const FETCH_CRYPTOS_SUCCESS = "FETCH_CRYPTOS_SUCCESS";
export const FETCH_CRYPTOS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const ADD_CRYPTO = "ADD_CRYPTO";
export const REMOVE_CRYPTO = "REMOVE_CRYPTO";

export const ADD_COLUMN = "ADD_COLUMN";
export const REMOVE_COLUMN = "REMOVE_COLUMN";
export const SET_COLUMNS = "SET_COLUMNS";
export const SET_COLUMNS_THAT_ARE_VISIBLE = "SET_COLUMNS_THAT_ARE_VISIBLE";
