export const TOGGLE_DATA_MENU = "TOGGLE_DATA_MENU";
export const CLOSE_DATA_MENU = "CLOSE_DATA_MENU";

export const UPDATE_CURRENT_DATA = "UPDATE_CURRENT_DATA";

export const LOAD_INITIAL_COLUMN_DATA = "LOAD_INITIAL_COLUMN_DATA";
export const EMPTY_HISTOGRAM_DATA = "EMPTY_HISTOGRAM_DATA";
export const PROCESS_NEW_COLUMN_DATA = "PROCESS_NEW_COLUMN_DATA";
export const UPDATE_LIVE_COLUMN_VIEW = "UPDATE_LIVE_COLUMN_VIEW";
export const GET_CURRENT_SELECTED_COLUMN = "GET_CURRENT_SELECTED_COLUMN";

export const FETCH_CRYPTOS_BEGIN = "FETCH_CRYPTOS_BEGIN";
export const FETCH_CRYPTOS_SUCCESS = "FETCH_CRYPTOS_SUCCESS";
export const FETCH_CRYPTOS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const ADD_FILTER_PARAMETER = "ADD_FILTER_PARAMETER";
